// constant list
export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const USER_ADDED_TO_LIST = "USER_ADDED_TO_LIST";
export const USER_DELETE_FROM_LIST = "USER_DELETE_FROM_LIST";
export const DELETE_ALL_USERS_FROM_LIST = "DELETE_ALL_USERS_FROM_LIST";
